# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Binutil < Formula
  desc "Helpers for converting to and from binary and string representations"
  homepage "https://github.com/bbengfort/binutil"
  version "1.0.0"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bbengfort/binutil/releases/download/v1.0.0/binutil_1.0.0_darwin_amd64.tar.gz"
      sha256 "f5719e6de97fcf5f87d1cafebae42292a7668e2734219144b4037f8f3b8d9729"

      def install
        bin.install "binutil"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bbengfort/binutil/releases/download/v1.0.0/binutil_1.0.0_darwin_arm64.tar.gz"
      sha256 "e9ef51ba9b2dba32257d2b2e4c9e3d27c911c343dd77f0b9cb92c08bbb5425dd"

      def install
        bin.install "binutil"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bbengfort/binutil/releases/download/v1.0.0/binutil_1.0.0_linux_arm64.tar.gz"
      sha256 "1b7b19dde921370635d7e8e1c94b4af35844f5cd78b1d9f2c674300d8331e545"

      def install
        bin.install "binutil"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bbengfort/binutil/releases/download/v1.0.0/binutil_1.0.0_linux_amd64.tar.gz"
      sha256 "8fd456b9ceb3fb4fdc19772106770f65ad7882c4972abf35e700469430eb1015"

      def install
        bin.install "binutil"
      end
    end
  end

  test do
    system "#{bin}/binutil", "--version"
  end
end
