# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whisper < Formula
  desc "Create and fetch whisper secret messages and files via the command-line"
  homepage "https://whisper.rotational.dev"
  version "1.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rotationalio/whisper/releases/download/v1.2.1/whisper_1.2.1_darwin_amd64.tar.gz"
      sha256 "d65dcaf5950702eefe77145f81d76d3b29d01e5d8bbe8347832e2ce0d7117a03"

      def install
        bin.install "whisper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rotationalio/whisper/releases/download/v1.2.1/whisper_1.2.1_darwin_arm64.tar.gz"
      sha256 "a85f9357918b5dfb201927bc58e55915e59c3de2c11a337bcc51c65c635e9ba0"

      def install
        bin.install "whisper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rotationalio/whisper/releases/download/v1.2.1/whisper_1.2.1_linux_arm64.tar.gz"
      sha256 "77f88ad6dfdd696c50de0167ecff5dfcca3e97e3adc419f6347fa8401e6986dc"

      def install
        bin.install "whisper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rotationalio/whisper/releases/download/v1.2.1/whisper_1.2.1_linux_amd64.tar.gz"
      sha256 "8629382deae079e62b707126ea9549c68c98c5d1a920648fa3be47a320dc6cc0"

      def install
        bin.install "whisper"
      end
    end
  end

  test do
    system "#{bin}/whisper", "--version"
  end
end
