# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whisper < Formula
  desc "Create and fetch whisper secret messages and files via the command-line"
  homepage "https://whisper.rotational.dev"
  version "1.1.1"
  license "Apache-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rotationalio/whisper/releases/download/v1.1.1/whisper_1.1.1_darwin_amd64.tar.gz"
      sha256 "057be8171c2c69ec42c4f1abbb74f5295b226a930602261af52647d20a55265e"
    end
    if Hardware::CPU.arm?
      url "https://github.com/rotationalio/whisper/releases/download/v1.1.1/whisper_1.1.1_darwin_arm64.tar.gz"
      sha256 "613b5a3c65538475a3dc3a357d590d653140425d410b869744625ab524cdb990"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rotationalio/whisper/releases/download/v1.1.1/whisper_1.1.1_linux_amd64.tar.gz"
      sha256 "4c1ec773473d4a8b54f354d287ffdf6386f3a31ef104321769e2f9e8ea8fbc7f"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rotationalio/whisper/releases/download/v1.1.1/whisper_1.1.1_linux_arm64.tar.gz"
      sha256 "4d857df516206e4ac60f3ac3b300a1bdff31f85ec08bc879662638f305d49e3d"
    end
  end

  def install
    bin.install "whisper"
  end

  test do
    system "#{bin}/whisper", "--version"
  end
end
